version: 2

jobs:

  build:

    working_directory: ~/circleci

    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run: mvn test
